### ISSUE TITLE
In BO, display issues of menu elements after drag&drop

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/seopresta-menu#1]
**Display of the menu in BO :**
When i drag&drop elements of the menu, 
sometimes elements are hidden, sometimes they are duplicated 
and when i refresh or when i update the menu, they are visible. 

**Display of the menu in FO :**
the issue only occurs in BO, in FO the menu is visible and not affected.   

[BO-Move-menu-hidden.zip](https://github.com/PrestaShop/seopresta-menu/files/2318657/BO-Move-menu-hidden.zip)

**Comment by PrestaSafe** [comment]
I think it's an ajax problems. 
i've mad an ajax loader and now it works fine
