### ISSUE TITLE
In BO, bulk remove item from menu issues

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/seopresta-menu#10]
**This issue is not critical**
In BO, When i select parent of category, children are not always selected and if i remove item, all item are removed. 
When parent category is selected, every item lower should be selected in order to know which item will be removed. 
If i check a parent element, sub categories should be checked and we should disable the uncheck of sub
categories and allowing only unchecking of parent element. 
[Delete-bulk.zip](https://github.com/PrestaShop/seopresta-menu/files/2324443/Delete-bulk.zip)

**Comment by PrestaSafe** [comment]
This the "CleanDB", 
If an item doesn't have a parent, or if this parent doesn't exist, it's auto deleted.

**Comment by PrestaSafe** [comment]
Instead of remove items in DB, i put them as root item(s).
