### ISSUE TITLE
Addons-like feedback

### ISSUE THREAD

**Issue by MrBaiame** [PrestaShop/seopresta-menu#13]
Hello,

You will probably get another feedback from the core team, but I reviewed your module like I would review an addons submission : 

- we do not allow ajax.php files anymore, you have to use a controller for your ajax calls
- /seoprestamenu.php:99 --> there is a query with non casted variables
- /seoprestamenu.php:336  --> there is a query with non casted variables
- i think the config_fr.xml should not be in the repo
- There seems to be quite a lot of HTML in the ajax.php file, you should use a TPL instead

Bests,

Alexis

**Comment by PrestaSafe** [comment]
Hi, i will fixed the casted variables, and i will fixed the other things in the futur update. 
Why making an adminController if there is no listing in backoffice ? Only for ajax ? it's big no ?

**Comment by Quetzacoalt91** [comment]
Controller don't always have to display something on the screen to be valid. Creating a controller just to handle ajax requests is fine.

By creating a controller, you will go through the PrestaShop process, with the request dispatching, the security checks, the hooks being triggered and so on. As our main concern is the security, we'd appreciate that requests are handled by controller methods.

 This is a point in progress on the core itself: https://github.com/PrestaShop/PrestaShop/pull/10131 We want to get rid of these entrypoints.

**Comment by PrestaSafe** [comment]
Ok, i'll make it quickly.

**Comment by PrestaSafe** [comment]
Now fixed [https://github.com/PrestaShop/seopresta-menu/commit/c954baa3c95623b9119b04c6995c2f74b31db4f6](url)
