### ISSUE TITLE
In FO : mobile version of the menu should be like the new one. 

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/seopresta-menu#15]
We updated the mobile version of the other module menu and it will be cool if the new module had a similar behaviour. 

We expect little changes

2) We should have one menu. Remove Navigation bloc menu and keep top hamburger menu 
3) When we open hamburger menu, we need it to take 100% of the screen

6) We would love to show the menu, hide submenus and have arrow down which become arrow top when we open submenu (check lasts screens).

Don't hesitate to check PR about the update of mobile version of the menu for more information : PrestaShop/PrestaShop/pull/10229

Currently : 
![mobile1](https://user-images.githubusercontent.com/40759259/45887762-c7e56100-bdbc-11e8-8a95-951d8aaa2e3f.png)
![menutopopen](https://user-images.githubusercontent.com/40759259/45887765-ca47bb00-bdbc-11e8-8962-924e0bef1c8a.png)
![menubotopen](https://user-images.githubusercontent.com/40759259/45887768-cc117e80-bdbc-11e8-8ca3-50c094a4a50b.png)

Expected results : 

![screen_shot_2018-09-21_at_15 51 11](https://user-images.githubusercontent.com/40759259/45889258-42fc4680-bdc0-11e8-95fc-e7faa0cdea92.png)

![screen_shot_2018-09-21_at_15 50 53](https://user-images.githubusercontent.com/40759259/45889267-48599100-bdc0-11e8-901c-18b23df97fc9.png)

Thanks.

**Comment by PrestaSafe** [comment]
This is a default install in the version 1.7.4.3: 
<img width="640" alt="capture d ecran 2018-10-17 a 13 22 53" src="https://user-images.githubusercontent.com/4788787/47083061-dda94300-d20f-11e8-8d10-5c2471e62210.png">

1. Logo should be aligned vertically with the top burger menu icon
 => Prestashop native default

2. We should have one menu. Remove Navigation bloc menu and keep top hamburger menu
 Ok for that i'll do this

3. When we open hamburger menu, we need it to take 100% of the screen
=> I'll wheck if it's posssible, it depends of template structure.

4. When opened it could be great to push smoothly content right (if possible).
=> Not possible, Prestashop's Team can do this if they want.

5. We would love to have a search bar included in the menu and hidden when the menu is closed
=> not possible for now, it depend of ps_searchbar menu

6. We would to love show the menu, hide submenus and have arrow down which become arrow top 
when we open submenu (check lasts screens).
=> i'll check that 

7. When the menu is open, user shouldn't be able to scroll.
=> Classic template default structure need to be changed.

I can't correct everything in PrestaShop default template.

Thanks.

**Comment by PrestaSafe** [comment]
i fixed it, it's the best i can do (for design).
Thanks
