### ISSUE TITLE
In BO, loader shouldn't be visible and debit card icon removed

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/seopresta-menu#16]
1) In BO, when we update the menu, a loader appear.
The loader should be totally invisible for the user. 

2) In BO, the little icon of debit card in top left corner  should be removed. 
![modifs](https://user-images.githubusercontent.com/40759259/46028911-20d13400-c0f2-11e8-9e99-18d704c209ec.png)

**Comment by PrestaSafe** [comment]
Removed
