### ISSUE TITLE
In BO, menu configuration isn't responsive. (<992px screen) 

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/seopresta-menu#17]
In BO, under 992px 
we can't delete items of the menu because there is superposition of menu items and "language" button

solution : under 992px add additional spacing (50px) to the div of menu elements

Current behaviour : 
![superposition](https://user-images.githubusercontent.com/40759259/46071030-7142a300-c17f-11e8-8911-a1ffe1ba2ea0.png)

Expected behaviour : 
![spaced](https://user-images.githubusercontent.com/40759259/46071031-7142a300-c17f-11e8-9370-943c5f2d9cd0.png)

**Comment by PrestaSafe** [comment]
Fixed
