### ISSUE TITLE
SQL requests to be sanitized

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/seopresta-menu#18]
In this example, 
https://github.com/PrestaShop/seopresta-menu/blob/3a0a58040912c15b1718d8afc8bf0361c2cdd873/seoprestamenu.php#L330-L334

It appears your variables are not protected against SQL injections. Please use the `pSQL()` method for strings and the `(int)` cast for numeric values.

**Comment by PrestaSafe** [comment]
Done [https://github.com/PrestaShop/seopresta-menu/commit/c954baa3c95623b9119b04c6995c2f74b31db4f6](url)
