### ISSUE TITLE
In BO, new text label for specific language is not saved

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/seopresta-menu#2]
When i change label of category and save, it’s changed in BO for the language choosed to create the menu but for other language its not changed. 

This is functional for CMS pages, custom links and products 

[Edit menu.zip](https://github.com/PrestaShop/seopresta-menu/files/2370273/Edit.menu.zip)

**Comment by PrestaSafe** [comment]
ok for text labels, but for categoryTree, i can't reload it dynamically for now. 
It will be in a new feature.

**Comment by PrestaSafe** [comment]
open new issue for categoryTree: #12
