### ISSUE TITLE
In BO drag and drop issues of menu elements 

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/seopresta-menu#3]
When i move menu elements, sometimes they disappear sometimes they are duplicated. 
**This affect only BO, in FO it work well.**

- Either the element is duplicated in its state before moving and then it disappears when the menu is updated
- Or the element disappear and reappear when the menu is updated. 

[Move menu.zip](https://github.com/PrestaShop/seopresta-menu/files/2370365/Move.menu.zip)

**Comment by PrestaSafe** [comment]
Dupplicate reload, fixed
